### ISSUE TITLE
[DOCS]: Build Fails

### ISSUE THREAD

**Issue by trevorb1** [DeltaE/delta-e-utils#34]
### Type of documentation issue.

Incorect

### Issue Description

The latest build is broken. See [this](https://readthedocs.org/projects/delta-e/builds/20727989/) build link. Seems like it a theme issue

### Additional Info

```bash
Running Sphinx v6.2.1
Creating file /home/docs/checkouts/readthedocs.org/user_builds/delta-e/checkouts/latest/docs/api/delta_e.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/delta-e/checkouts/latest/docs/api/delta_e.EPAEmissions.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/delta-e/checkouts/latest/docs/api/modules.rst.
making output directory... done
loading configurations for delta-e 0.0.post1.dev78+g17e4176 ...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/delta-e/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/delta-e/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/delta-e/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 340, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/delta-e/envs/latest/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 253, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/delta-e/envs/latest/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 304, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/delta-e/envs/latest/lib/python3.8/site-packages/sphinx/theming.py", line 228, in create
    raise ThemeError(__('no theme named %r found (missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'renku' found (missing theme.conf?)

Theme error:
no theme named 'renku' found (missing theme.conf?)
```

**Comment by Lakshay-sethi** [comment]
Issue resolved 
PR: https://github.com/DeltaE/delta-e-utils/pull/35
